# Generated by Django 6.0.3 on 2026-03-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shoppost_shoppostimage_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppost',
            name='caption',
            field=models.TextField(blank=True, help_text='Description de la publication'),
        ),
        migrations.AlterField(
            model_name='shoppost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, help_text="Prix si c'est un produit ou service", max_digits=10, null=True),
        ),
    ]
