# Generated by Django 6.0.3 on 2026-03-20 23:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('booking_new', '📅 Nouvelle réservation'), ('booking_confirmed', '✅ Réservation confirmée'), ('booking_cancelled', '❌ Réservation annulée'), ('booking_reminder', '⏰ Rappel de rendez-vous'), ('review_new', '⭐ Nouvel avis'), ('message_new', '💬 Nouveau message'), ('promo', '🎉 Promotion'), ('system', '🔔 Système')], max_length=25)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=250)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
